@startuml GameState FSM

[*] --> gameSetup
gameSetup --> placingShips: createPlayers()
placingShips --> placingShips: placeShip(),\nplaceRandomShips()
placingShips --> shotReceived: startGame()
shotReceived --> shotPrimed: primeShot()
shotPrimed --> shotReceived: makeShot()
shotReceived --> gameOver: checkIfGameOver() === true 
gameOver --> gameSetup

@enduml
